version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - crm-net
    depends_on:
      - frontend

  consumer-ingest:
    build: ./backend
    command: ["node", "src/consumers/ingestConsumer.js"]
    env_file:
      - ./backend/.env
    networks:
      - crm-net
    depends_on:
      - backend

  consumer-receipts:
    build: ./backend
    command: ["node", "src/consumers/receiptConsumer.js"]
    env_file:
      - ./backend/.env
    networks:
      - crm-net
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - crm-net

networks:
  crm-net:
    driver: bridge