version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - crm-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - crm-net

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: crm
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - crm-net

volumes:
  mysql-data:

networks:
  crm-net: